### ISSUE TITLE
It would be great if we can generate one word random outputs with this library

### ISSUE THREAD

**Issue by dulara1994** [shinshin86/random-fruits-name.js#5]
This is a feature request:

I can get the max benefit of this library if there is a way to generate only one-word output. 

eg: Apple
      Banana

The problem is the inability of forcing the library not to generate random fruit name with multiple words. basically to avoid "SUGAR BABY WATERMELON", "KING COCONUT" like fruit names because they have more than 1 word. 

I am expecting something like 

`getRandomFruitsName({maxWords: 1}); `which will ensure it will only return one word fruit name.

Thank you.!

**Comment by shinshin86** [comment]
@dulara1994 Hello.
Sorry for the late reply.

That's an interesting idea!
I am going to consider whether it is feasible.
Thanks for the great ideas!

**Comment by shinshin86** [comment]
@dulara1994  I've come up with an implementation based on your ideas.
I think the function design would look like this.
(The `maxWords` would be an option in the second argument.)

```javascript
getRandomFruitsName(lang, option)
```

Example:

```javascript
getRandomFruitsName('en', {maxWords: 1})
```

**Comment by shinshin86** [comment]
@dulara1994 Added `maxWords` option.
I've released it on npm, so you could install the latest version and give it a try.
https://www.npmjs.com/package/random-fruits-name#option

**Comment by shinshin86** [comment]
This issue is close.
If you have any requests or issues, please create a new issue.

Thanks for the great idea!
